
name: CI

on:
  push:
    branches:
      - main
    tags:
      - v*.**

permissions:
  contents: read
  packages: write

jobs:
  ci:
    name: Build Docker Image
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        encryption: [ '' ]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker login
        run: |
          docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}

      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Set tags
        run: |
          if [[ "${{ github.ref }}" == "${{ env.RELEASE_VERSION }}" ]]; then
             echo "RELEASE_TAG=latest" >> $GITHUB_ENV
          else
             echo "RELEASE_TAG=${{ env.RELEASE_VERSION }}" >> $GITHUB_ENV
          fi

      - name: Build and push to GitHub Packages
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64, linux/arm64
          push: true
          tags: |
            ghcr.io/jony-byqc/image_deploy/image_deploy:${{ env.RELEASE_TAG }}
          file: Dockerfile
