name: Release
on:
  push:
    tags:
      - 'v*.**'

permissions:
  contents: write

jobs:
  release:
    name: Build
    runs-on: ubuntu-22.04
    steps:

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Create github releases
        run: npx changelogithub
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Generate a changelog
        uses: orhun/git-cliff-action@v2
        with:
          config: cliff.toml
          args: --verbose
        env:
          OUTPUT: CHANGELOG.md

      - name: Extract branch name
        shell: bash
        run: |
          raw=$(git branch -r --contains ${{ github.ref }} | grep release)
          echo "raw is $raw."
          branch=${raw#*/}
          echo "Branch is $branch."
          echo "branch=$branch" >> $GITHUB_OUTPUT
        id: extract_branch

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update ChangeLog
          file_pattern: 'CHANGELOG.md'
          branch: ${{ steps.extract_branch.outputs.branch }}